alias acs='apt-cache search '
alias agi='apt-get install '
alias agu='apt-get update'
alias sudo='sudo '
alias aar='add-apt-repository '
alias agp='apt-get purge '
alias cinnamon_restart='killall cinnamon && export DISPLAY=:0.0 && cinnamon --replace &'
alias fuck='sudo $(history -p \!\!)'
alias aga='apt-get autoremove'
alias rm='trash'
alias ..='cd ..'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias ....='cd ../..'
alias pyvenv='pyvenv-3.4'
alias mkvenv='mkvirtualenv --python=/usr/bin/python3 '
alias mkvenv3.4='mkvirtualenv --python=/usr/bin/python3.4 '
